var STRINGS;
var STRINGS_EN = {
    "page.title": "Personal Webpage of Kevin Kramer",
    "page.shorttitle": "Kevin Kramer",
    "page.subtitle": "Curriculum Vitae, documents and more",
    //
    "navi.home": "Home",
    "navi.about": "About",
    "navi.about.long": "A few words about me",
    "navi.cv": "CV",
    "navi.cv.long": "Curriculum Vitae",
    "navi.docs": "Portfolio",
    "navi.docs.short": "Portfolio",
    "navi.contact": "Contact",
    //
    "welcome": "Welcome to Kevin Kramer's web page!",
    "about": "<p>At the age of 20 I found myself in the lucky and luxurious position of being overwhelmed by too many options regarding what I should study. Driven by the not so humble goal of wanting to understand the universe, I chose to enter and dive down into the field of physics. Two degrees and a PhD later I may not have quite reached that goal, but I have seen and gained so much along the way that there are no regrets whatsoever. In addition to acquiring a physicist's analytical toolset and an experimentalist's collaborative skills, flexibility and perseverance, this path has also opened me up for the beauty of programming. Furthermore, my appreciation of the world we live in has only grown with each increase in understanding of the interconnections and laws of nature.</p><p>Born and raised in Switzerland, I hold a deep love for the beauty of the mountains, lakes, rivers and forests. In my free time I enjoy gardening and preparing food with and for others. Also, I love to dabble in creating musical vibrations with any instrument I can get my hands on.</p><p>I harbor the deep wish to put my acquired skills and interests in the natural world to use for some of society's challenges.</p>",
    //
    "docs.desc": "Below you may find download links to several documents which hopefully can be of use or interest.",
    "docs.cv": "<a href=\"documents/cv_kevin_kramer_en.pdf\">Download PDF version of CV.</a>",
    "docs.cv.desc": "A classic \"paper\" version of my CV in pdf format.",
    "docs.phd": "PhD thesis",
    "docs.phd.desc": "Summarizes most of the published work resulting during my four years PhD studies. Keywords: angle-resolved photoemission spectroscopy, superconductors, quantum materials.",
    "docs.msc": "Master thesis",
    "docs.msc.desc": "A nine month project on 2D semiconductors carried out at the University of Amsterdam. Time-resolved photoluminescence.",
    "docs.bsc": "<a href=\"documents/bachelor_thesis_kevin_kramer.pdf\">Bachelor thesis</a>",
    "docs.bsc.desc": "Assembly of a fluorescence-microscopy setup, simulations and experimental measurements were carried out to determine a key parameter of nanofludic devices.",
    "portfolio.growR": "growR",
    "portfolio.growR.desc": "An R package that implements a vegetation growth model. It provides functionalities to calibrate the model, run complete simulations and to visualize and analyze the outputs.",
    "portfolio.ds": "data-slicer",
    "portfolio.ds.desc": "A data analysis framework which resulted from the heavy-duty analysis of loads of 3D ARPES datasets. Besides tools and widgets for general multi-dimensional data visualization, this contains a GUI for quick inspection of 3D data.",
    "portfolio.hpc": "Hydrodynamic Simulation",
    "portfolio.hpc.desc": "A project carried out within the High Performance Computing course at UZH. The goal was to implement the hydrodynamic Navier-Stokes equations and employ parallelization to simulate a relatively large system on a supercomputing cluster at the Swiss center for scientific computing (CSCS). The code was implemented in C++ and the Message Passing Interface (MPI) was used for the parallelization.",
    "portfolio.cern": "PET Simulations",
    "portfolio.cern.desc": "The simulation tools Geant4 and GATE were used to experiment with novel ideas for positron-emission tomography geometries. This was done in the framework of the <a href=\"https://dissertori-group.ethz.ch/research/detector-rd-and-applications-in-biomedical-imaging/safir.html\" target=\"_blank\">SAFIR project</a>. Additional studies were undertaken with python.",
    //
    "contact.address": "Kevin Kramer<br>Physik Institut<br>Universität Zürich<br>Winterthurerstrasse 190<br>8057 Zürich",
   //"contact.address": "Kevin Kramer<br>Yumo-Park 12<br> 5415 Nussbaumen",
    "contact.email": "<a href=\"mailto:kevin.pasqual.kramer@proton.me\">kevin.pasqual.kramer@proton.me</a>",
    "contact.references": "References",
    "contact.pierluigi.title": "Project leader Agroscope",
    "contact.pierluigi.address": "Dr. Pierluigi Calanca<br>Agroscope<br>Reckenholzstrasse 191<br>8046 Zürich<br>Phone +41 58 46 87512<br><a href=\"mailto:pierluigi.calanca@agroscope.admin.ch\">pierluigi.calanca@agroscope.admin.ch</a>",
    "contact.johan.title": "PhD supervisor",
    "contact.johan.address": "Prof. Dr. Johan Chang<br>University of Zurich<br>Department of Physics<br><a href=\"mailto:johan.chang@uzh.ch\">johan.chang@uzh.ch</a><br>+4144 635 5748",
    "contact.antonio.title": "Master thesis supervisor",
    "contact.antonio.address": "Dr. Antonio Capretti<br><a href=\"https://www.surfly.com/about/\">Surfly</a><br><a href=\"https://www.linkedin.com/in/capretti/\">LinkedIn</a>",
    "contact.werner.title": "SAFIR project leader",
    "contact.werner.address": "Dr. Werner Lustermann<br>CERN/ETHZ<br>Department of Physics<br><a href=\"mailto:luster@ethz.ch\">luster@ethz.ch</a><br>+4122 767 6520",
    // CV Education
    //"cv.edu": "Education",
    "cv.edu": "",
    "cv.edu.agroscope": "Postdoctoral Researcher",
    "cv.edu.agroscope.sub": "Influence of Climate Change on Swiss Agriculture",
    "cv.edu.agroscope.time": "2023 - 2025",
    "cv.edu.agroscope.place": "Agroscope",
    "cv.edu.postdoc": "Postdoctoral Researcher",
    "cv.edu.postdoc.sub": "Quantum Matter",
    "cv.edu.postdoc.time": "2022 - 2023",
    "cv.edu.postdoc.place": "Laboratory for Quantum Matter Research, University of Zurich",
    "cv.edu.phd": "PhD in Physics",
    "cv.edu.phd.sub": "Quantum Matter and Spectroscopy",
    "cv.edu.phd.time": "2018 - 2022",
    "cv.edu.phd.place": "Laboratory for Quantum Matter Research, University of Zurich",
    "cv.edu.msc": "Master of Science",
    "cv.edu.msc.sub": "Condensed Matter Physics",
    "cv.edu.msc.time": "2016-2018",
    "cv.edu.msc.place": "University of Zurich with thesis work carried out at the University of Amsterdam",
    "cv.edu.cern": "Internship at CERN",
    "cv.edu.cern.sub": "Member of the SAFIR project. Data acquisition and analysis, Monte Carlo simulations, C++, python, mongoDB",
    "cv.edu.cern.time": "2015",
    "cv.edu.cern.place": "ETH Zürich & CERN, Geneva",
    "cv.edu.bsc": "Bachelor of Science",
    "cv.edu.bsc.sub": "Major: Physics, Minor: Information Technology",
    "cv.edu.bsc.time": "2011-2014",
    "cv.edu.bsc.place": "University of Zurich",
    "cv.edu.matura": "Swiss Matura",
    "cv.edu.matura.sub": "Biology and Chemistry",
    "cv.edu.matura.time": "2003-2009",
    "cv.edu.matura.place": "Kantonsschule Limattal",
    // CV work history and services
    "cv.past": "Services",
    "cv.past.time": "Time",
    "cv.past.function": "Function",
    "cv.past.joss": "Referee for the Journal of Open Source Software",
    "cv.past.joss.time": "since 2022",
    "cv.past.fire": "Fire brigade Obersiggenthal",
    "cv.past.fire.time": "since 2022",
    "cv.past.sustcom": "Founding member of the Institute of Physics's Sustainability Committee",
    "cv.past.sustcom.time": "2021-2022",
    "cv.past.s4f": "Active member of Scientists 4 Future Switzerland",
    "cv.past.s4f.time": "2020-2022",
    "cv.past.jrep": "Junior Researcher representative in the Faculty Assembly at UZH",
    "cv.past.jrep.time": "2018-2021",
    "cv.past.civil": "Civil Service<br>Served on a Swiss alp: construction of fences, herding and milking of cows, pasture mainenance.",
    "cv.past.civil.time": "Spring 2018",
    "cv.past.army": "Compulsory military service<br>Paramedic and truck driver.",
    "cv.past.army.time": "2010",
    "skills.title": "Skills and interests",
    "skills.physics.title": "Physics",
    "skills.physics": "Angle-resolve photoemission spectroscopy, density functional theory, cuprate high-temperature superconductors, heavy fermion systems, fluorescence microscopy, (time-resolved) photoluminescence, transition metal dichalcogenides",
    "skills.ai.title": "Computational methods and AI",
    "skills.ai": "high performance computing, simulations, machine and deep learning, parallelisation, visualization, data analysis, automation",
    "skills.it.title": "Programming",
    "skills.it": "python, matlab, Linux/UNIX, LaTeX, Java, C++, database systems (mongoDB), HTML5, CSS",
    "skills.technical.title": "Technical experience",
    "skills.technical": "Assembly of a fluorescence microscopy setup, assembly of a cryo-photoluminescence setup, over 20 ARPES beamtimes",
    "skills.teaching.title": "Teaching",
    "skills.teaching": "Years of experience in teaching exercise classes and labs for different audiences, from Physics Master students to would-be high school teachers, all of which I've enjoyed very much",
    "skills.languages.title": "Languages",
    "skills.languages": "German (native), English (fluent), French (basic), Italian (basic), Dutch (beginner)"
};
var STRINGS_DE = {
    "page.title": "Kevin Kramer's Bewerbungswebsite",
    "page.shorttitle": "Kevin Kramer",
    "page.subtitle": "Lebenslauf, Dokumente und mehr",
    //
    "navi.home": "Home",
    "navi.about": "Über",
    "navi.about.long": "Einige Worte über mich",
    "navi.cv": "Lebenslauf",
    "navi.cv.long": "Lebenslauf",
    "navi.docs": "Portfolio",
    "navi.docs.short": "Portfolio",
    "navi.contact": "Kontakt",
    //
    "welcome": "Willkommen auf Kevin Kramer's webpage!",
    "about": "<p>Im Alter von 20 Jahren befand ich mich in der glücklichen und luxuriösen Position, von den vielen Möglichkeiten im Bezug auf meine Studienwahl überwältigt zu sein. Angetrieben von einer tiefen und vielleicht naiven Neugierde nach den Grundgesetzen des Universums entschied ich mich schliesslich dazu, in das Feld der Physik einzutauchen. Zwei Abschlüsse und einen Doktortitel später habe ich zwar das Universum immer noch nicht verstanden, aber unterwegs so viel gesehen, erlebt und gelernt dass es wahrlich nichts zu bedauern gibt. Nebst dem Aneignen der analytischen Wekzeuge eines Physikers und den kollaborativen Fähigkeiten, der Flexibilität und dem Durchhaltevermögen eines Experimentators hat mir dieser Pfad auch die Schönheit des Programmierens eröffnet. Ausserdem ist meine Wertschätzung für die Wunder der Welt nur gewachsen mit dem immer grösseren Verständnis für die Zusammenhänge und Gesetze in der Natur.</p><p>Gebürtig in der Schweiz hege ich seit jeher eine tiefe Liebe und Verbundenheit für die Schönheit der Berge, Seen, Flüsse und Wälder. In meiner freien Zeit geniesse ich es zu gärtnern und für und mit anderen Essen zuzubereiten. Ausserdem liebe ich es musikalische Vibrationen zu erzeugen mit jedem Instrument das ich in die Finger kriege.</p><p>Ich hege den tiefen Wunsch meine Fähigkeiten und Interessen in den Dienst einer Lösung für die Herausforderungen der Gesellschaft zu stellen.</p>",
    //
    "docs.desc": "Hier finden sich Download-Links zu verschiedenen Dokumenten die hoffentlich von Nutzen oder Interesse sein können.",
    "docs.cv": "<a href=\"documents/cv_kevin_kramer_de.pdf\">Lebenslauf als PDF-Download.</a>",
    "docs.cv.desc": "Eine klassische 'Papierversion' des Lebenslaufs als PDF.",
    "docs.phd": "<a href=\"documents/PhD_thesis_Kevin_Kramer_211020.pdf\">Doktorarbeit (englisch)</a>",
    "docs.phd.desc": "Fasst den Grossteil der Forschungs- und Entwicklungsarbeit während meines vierjährigen Doktoratstudiums zusammen. Stichwörter: winkelaufgelöste Photoelektronenspektroskopie, Supraleiter, Quantenmaterialien.",
    "docs.msc": "<a href=\"documents/master_thesis_kevin_kramer.pdf\">Masterarbeit (englisch)</a>",
    "docs.msc.desc": "Ein neunmonatiges Projekt über zeitaufgelöste Photolumineszenz von 2D Halbleitern. Die Arbeit wurde an der Universität Amsterdam getätigt.",
    "docs.bsc": "<a href=\"documents/bachelor_thesis_kevin_kramer.pdf\">Bachelorarbeit (englisch)</a>",
    "docs.bsc.desc": "Ein Fluoreszenzmikroskop wurde aufgebaut und Simulationen und experimentelle Messungen durchgeführt um einen Schlüsselparameter in der Charakterisierung von Nano-Fluidchips zu bestimmen.",
    "portfolio.growR": "growR",
    "portfolio.growR.desc": "Ein R Paket das ein Vegetationswachstumsmodell implementiert. Es beinhält Funktionalitäten zur Modellkalibrierung und zur Durchführung kompletter Simulationen sowie zur Analyse und Darstellung der Resultate.",
    "portfolio.ds": "data-slicer",
    "portfolio.ds.desc": "Ein System zur Datenanalyse, das entstanden ist als Resultat der intensiven Verarbeitung von 3D ARPES Datensätzen. Neben Werkzeugen und Widgets für multidimensionale Datenanalyse und -visualisierung beinhaltet das Paket ein GUI für die schnelle Inspektion von 3D Daten.",
    "portfolio.hpc": "Hydrodynamische Simulation",
    "portfolio.hpc.desc": "Ein Projekt das im Rahmen des Kurses 'High Performance Computing' an der UZH durchgeführt wurde. Ziel war es, die hydrodynamischen Navier-Stokes Gleichungen zu implementieren und mittels Parallelisierung auf einem Supercomputer des Schweizerischen Zentrums für wissenschaftliche Berechnungen (CSCS) durchzurechnen. Der Code wurde in C++ geschrieben und mit dem Message Passing Interface (MPI) parallelisiert.",
    "portfolio.cern": "PET Simulationen",
    "portfolio.cern.desc": "Die Simuliertools Geant4 und GATE wurden eingesetzt um mit neuen Ideen für Geometrien eines Positrons-Emissions Tomographen zu experimentieren. Dies wurde im Rahmen des<a href=\"https://dissertori-group.ethz.ch/research/detector-rd-and-applications-in-biomedical-imaging/safir.html\" target=\"_blank\">SAFIR Projekts</a> am CERN und mit der ETHZ durchgeführt. Zusätzliche Studien wurden in python angelegt.",
    //
    "contact.address": "Kevin Kramer<br>Physik Institut<br>Universität Zürich<br>Winterthurerstrasse 190<br>8057 Zürich",
   //"contact.address": "Kevin Kramer<br>Yumo-Park 12<br> 5415 Nussbaumen",
    "contact.email": "<a href=\"mailto:kevin.pasqual.kramer@proton.me\">kevin.pasqual.kramer@proton.me</a>",
    "contact.references": "Referenzen",
    "contact.pierluigi.title": "Projektleiter Agroscope",
    "contact.johan.title": "Gruppenleiter UZH",
    "contact.johan.address": "Prof. Dr. Johan Chang<br>Universität Zürich<br>Physik Institut<br><a href=\"mailto:johan.chang@uzh.ch\">johan.chang@uzh.ch</a><br>+4144 635 5748",
    "contact.antonio.title": "Betreuer Masterarbeit",
    "contact.antonio.address": "Dr. Antonio Capretti<br><a href=\"https://www.surfly.com/about/\">Surfly</a><br><a href=\"https://www.linkedin.com/in/capretti/\">LinkedIn</a>",
    "contact.werner.title": "Projektleiter SAFIR (CERN)",
    "contact.werner.address": "Dr. Werner Lustermann<br>CERN/ETHZ<br>Departement Physik<br><a href=\"mailto:luster@ethz.ch\">luster@ethz.ch</a><br>+4122 767 6520",

    // CV Education
    //"cv.edu": "Ausbildung",
    "cv.edu": "",
    "cv.edu.agroscope": "Wissenschaftlicher Mitarbeiter",
    "cv.edu.agroscope.sub": "Einfluss des Klimawandels auf die schweizer Landwirtschaft",
    "cv.edu.agroscope.time": "2023 - 2025",
    "cv.edu.agroscope.place": "Agroscope",
    "cv.edu.postdoc": "Promovierter Wissenschaftler",
    "cv.edu.postdoc.sub": "Quantenmaterie",
    "cv.edu.postdoc.time": "2022 - 2023",
    "cv.edu.postdoc.place": "Laboratory for Quantum Matter Research, Universität Zürich",
    "cv.edu.phd": "Doktorat in Physik",
    "cv.edu.phd.sub": "Quantenmaterie und Spektroskopie",
    "cv.edu.phd.time": "2018 - 2022",
    "cv.edu.phd.place": "Laboratory for Quantum Matter Research, Universität Zürich",
    "cv.edu.msc": "Master of Science",
    "cv.edu.msc.sub": "Physik der kondensierten Materie",
    "cv.edu.msc.time": "2016-2018",
    "cv.edu.msc.place": "Universität Zürich mit einer Masterarbeit an der Uni Amsterdam",
    "cv.edu.cern": "Praktikum am CERN",
    "cv.edu.cern.sub": "Mitglied des SAFIR-Projekts. Datenacquisition und -analyse, Monte Carlo Simulationen, C++, python, mongoDB",
    "cv.edu.cern.time": "2015",
    "cv.edu.cern.place": "ETH Zürich & CERN, Genf",
    "cv.edu.bsc": "Bachelor of Science",
    "cv.edu.bsc.sub": "Hauptfach: Physik, Nebenfach: Informatik",
    "cv.edu.bsc.time": "2011-2014",
    "cv.edu.bsc.place": "Universität Zürich",
    "cv.edu.matura": "Matura",
    "cv.edu.matura.sub": "Biologie and Chemie",
    "cv.edu.matura.time": "2003-2009",
    "cv.edu.matura.place": "Kantonsschule Limattal",
    // CV work history and services
    "cv.past": "Dienste",
    "cv.past.time": "Zeitraum",
    "cv.past.function": "Funktion",
    "cv.past.joss": "Rezensent für das Journal of Open Source Software",
    "cv.past.joss.time": "seit 2022",
    "cv.past.fire": "Feuerwehr Obersiggenthal",
    "cv.past.fire.time": "seit 2022",
    "cv.past.sustcom": "Gründungsmitglied der Nachhaltigkeitskommission des Physik Instituts",
    "cv.past.sustcom.time": "2021-2022",
    "cv.past.s4f": "Aktives Mitglied bei Scientists for Future Switzerland",
    "cv.past.s4f.time": "2020-2022",
    "cv.past.jrep": "Repräsentant des wissenschaftlichen Nachwuchses in der Mathematisch-Naturwissenschaftlichen Fakultät der UZH",
    "cv.past.jrep.time": "2018-2021",
    "cv.past.civil": "Zivildienst auf einer Alp: Auf- und Abbau von Zäunen, hüten und melken von Kühen, Pflege der Weiden.",
    "cv.past.civil.time": "Frühling 2018",
    "cv.past.army": "Militärdienst<br>Sanitäter und Lastwagenfahrer",
    "cv.past.army.time": "2010",
    "skills.title": "Fähigkeiten und Interessen",
    "skills.physics.title": "Physik",
    "skills.physics": "Winkelaufgelöste Photoelektronenspektroskopie, Dichtefunktionaltheorie, Hochtemparatursupraleitung, schwere Fermionen, Fluoreszenzmikroskopie, (zeitaufgelöste) Photolumineszenz, Übergangsmetalldichalkogenide",
    "skills.ai.title": "Computergestützte Methoden und künstliche Intelligenz",
    "skills.ai": "Hochleistungsrechnen, Simulationen, Maschinenlernen, Parallelisierung, Visualisierung, Datenanalyse, Automation",
    "skills.it.title": "Programmieren",
    "skills.it": "python, matlab, Linux/UNIX, LaTeX, Java, C++, database systems (mongoDB), HTML5, CSS",
    "skills.technical.title": "Technische Erfahrung",
    "skills.technical": "Bau eines Fluoreszenzmikroskops, Bau eines Kryo-Photolumineszenz Setups, über 20 ARPES Strahlzeiten",
    "skills.teaching.title": "Lehre",
    "skills.teaching": "Mehrjährige Erfahrung im Betreuen von Übungsgruppen und Laborversuchen vor verschiedenem Publikum, von Physik Masterstudierenden bis zu angehend Sekundarlehrpersonen; Aufgaben ich stets mit grosser Freude bewältigt habe",
    "skills.languages.title": "Sprachen",
    "skills.languages": "Deutsch (Muttersprachler), Englisch (fliessend), Französisch (Grundlagen), Italienisch (Grundlagen), Niederländisch (Anfänger)"
};
STRINGS = STRINGS_EN;
